import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Osta - منصة أسطى",
  description: "Generated by create next app",
};

const cairo = Cairo({
  subsets: ["arabic"],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={cairo.className} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
